### PR TITLE
Make UIViewHolder immutable

### LINKED ISSUE #1: Modifying state during view update, this will cause undefined behavior.
Hello,

First of all I like the idea behind this library! However in practice it doesn't look usable yet:
image

This is what I get in some toy project, however in a real use case this issue is actually hitting hard with a crash both in debug and release due to this precondition failure:
```
[error] precondition failure: setting value during update: 2072
```
As far as I see, all methods exposed by UIViewRepresentable are called during the view update, so no state can be changed there and the current approach seems to hit a dead end.

I'm using Xcode 13.2.1 on macOS 12.1.

### PR DESCRIPTION
**Pull request by auramagi**
# What

- Resolves #1 

Trying to update ideal size state right after UIView generation caused a run-time warning, since this was effectively modifying a `@State` during `body` access.

# How

- Don't update ideal size on UIView generation
  - We didn't really need this anyway, as we will always get at least one more update after the initial layout pass.
- Don't mutate `UIViewHolder` state, instead hold and update the calculated ideal size inside `UIViewAdaptor`

# Review Points

- Does this PR resolve the issue?
- Are there any other problems with this fix?

### CODE REVIEW

File: Sources/RepresentableKit/UIViewAdaptor.swift [hunk 1]
```diff
@@ -86,17 +88,14 @@ struct UIViewHolder<Content: UIView> {
...
+    func updateView(_ uiView: Content) {
         storage.view = uiView
         uiView.apply(flexibility: flexibility)
-        updateSize(proxySize: uiView.frame.size)
     }
     
-    mutating func updateSize(proxySize: CGSize) {
-        guard let uiView = storage.view else { return }
-        idealSize = idealSizeCalculator.viewIdealSizeInSize(uiView, proxySize)
+    func idealSize(proxySize: CGSize) -> IdealSize? {
```
Comment (el-hoshino) [inline Sources/RepresentableKit/UIViewAdaptor.swift:96]: Seems like we can make this private?

**Review by el-hoshino — APPROVED** [review]
LGTM

File: Sources/RepresentableKit/UIViewAdaptor.swift (hunk 1 above)
Comment (auramagi) [reply Sources/RepresentableKit/UIViewAdaptor.swift:96]: We can't since this function is called from outside this struct. Internal should be good enough IMO.
